### ISSUE TITLE
UIImagePickerController的导航栏不能正常显示

### ISSUE THREAD

**Issue by ZLEii** [Roen-Ro/RRViewControllerExtension#3]
你好作者，在iOS13里面，导入RRViewControllerExtension以后，选择照片的时候用presentViewController 弹出UIImagePickerController的时候，UIImagePickerController的导航栏会往下挪64个像素，不导入RRViewControllerExtension就是正常的。
![IMG_219B8E7CA03F-1](https://user-images.githubusercontent.com/17490233/91786275-d6d81d80-ec39-11ea-9ff7-01a69a206840.jpeg)

**Comment by Roen-Ro** [comment]
已经修复，UIImagePickerController本身隐藏了NavigationBar所致
